# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-worker-pool-1
  name: migrate-service-cluster-2-worker-pool-1 # kpt-set: ${cluster-name}-worker-pool-1
  namespace: config-control # kpt-set: ${project-namespace}
  labels:
    cluster: migrate-service-cluster-2 # kpt-set: ${cluster-name}
  annotations:
    cnrm.cloud.google.com/project-id: "my-awesome-project" # kpt-set: ${project-id}
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn-live'
spec:
  autoscaling:
    maxNodeCount: 3
    minNodeCount: 1
  clusterRef:
    name: migrate-service-cluster-2 # kpt-set: ${cluster-name}
  initialNodeCount: 1
  location: northamerica-northeast2 # kpt-set: ${region}
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    metadata:
      disable-legacy-endpoints: "true"
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS_CONTAINERD
    machineType: e2-standard-4 # kpt-set: ${machineType}
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    preemptible: false
    tags: # kpt-set: ${tags}
      - regional
      - northamerica
      - sandbox
