# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
data:
  ######
  # General Settings Values
  #
  # The following are Settings for the environment to bootstrap with
  #
  ######
  # GKE Sandbox Network Values
  ######
  network-name: gke-3-net
  routing-mode: REGIONAL # REGIONAL or GLOBAL
  mtu: "1460" # Range can be between 1460 and 1500 bytes
  subnetwork-name: gke-3-subnet
  subnet-cidr: 10.2.0.0/16
  log-aggregation-interval: INTERVAL_5_SEC # Possible Values ["INTERVAL_5_SEC", "INTERVAL_30_SEC", "INTERVAL_1_MIN", "INTERVAL_5_MIN", "INTERVAL_10_MIN", "INTERVAL_15_MIN"]
  flow-sampling: "0.5" # Value must be between 0 and 1
  log-metadata: INCLUDE_ALL_METADATA # Possible Values ["EXCLUDE_ALL_METADATA", "INCLUDE_ALL_METADATA", "CUSTOM_METADATA"]
  # log-metadatafields: | # Use if CUSTOM_METADATA is used for `log-metadata`
  #   - test 
  private-google-access: "true"
  gke-services-cidr: 10.7.0.0/16
  gke-pod-cidr: 10.8.0.0/16
  gke-pod-range-name: podrange
  gke-services-range-name: servicesrange
  ######
  #
  # GKE Sandbox Cluster Values
  # Creates a Private GKE Cluster with 1 Node Pool
  #
  ######
  project-id: project-id # Must be globally unique
  project-namespace: config-control
  location: northamerica-northeast2
  cluster-description: migrate-service-cluster-2
  cluster-name: migrate-service-cluster-2
  #####
  #
  # CIDR Range to be used for GKE Endpoint Access
  # https://cloud.google.com/kubernetes-engine/docs/how-to/authorized-networks
  #
  auth-network: |
    - cidrBlock: 35.237.152.134/32
      displayName: private-net
  tags: |
    - regional
    - northamerica
    - sandbox
  gke-admin: k8s-admin@domain.com
  gke-viewer: k8s-admin@domain.com
  ####
  #
  # Machine Type to be used for GKE Node Pool
  # https://cloud.google.com/compute/docs/machine-types
  #
  machineType: e2-standard-4
  ######
  #
  # Anthos Values
  #
  ######
  acm-version: 1.11.1 # Anthos Config Management Version https://cloud.google.com/anthos/config-management
