apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: migrate-service-cluster-acm
  annotations:
    cnrm.cloud.google.com/project-id: "my-awesome-project" # kpt-set: ${project-id}       
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
  namespace: config-control # kpt-set: ${project-namespace}
spec:
  projectRef:
    external: my-awesome-project # kpt-set: ${project-id}       
  location: global
  membershipRef:
    name: migrate-service-cluster
  featureRef:
    name: migrate-demo-config-management
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        policyDir: ""
        syncWaitSecs: "20"
        secretType: gcpserviceaccount
        gcpServiceAccountRef:
          external: config-sync-sa@my-awesome-project.iam.gserviceaccount.com # kpt-set: config-sync-sa@${project-id}.iam.gserviceaccount.com 
        syncRepo: "https://source.developers.google.com/p/my-awesome-project/r/my-awesome-project-migrate-demo" # kpt-set: https://source.developers.google.com/p/${project-id}/r/${project-id}-migrate-demo
        syncRev: "HEAD"
        syncBranch: "master"
    version: 1.10.2
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
      auditIntervalSeconds: "20"
    binauthz:
      enabled: true
    hierarchyController:
      enabled: false
      enablePodTreeLabels: false
      enableHierarchicalResourceQuota: false
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: migrate-service-cluster-2-acm
  annotations:
    cnrm.cloud.google.com/project-id: "my-awesome-project" # kpt-set: ${project-id}       
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
  namespace: config-control # kpt-set: ${project-namespace}
spec:
  projectRef:
    external: my-awesome-project # kpt-set: ${project-id}       
  location: global
  membershipRef:
    name: migrate-service-cluster-2
  featureRef:
    name: migrate-demo-config-management
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        policyDir: ""
        secretType: gcpserviceaccount
        gcpServiceAccountRef:
          external: config-sync-sa@my-awesome-project.iam.gserviceaccount.com # kpt-set: config-sync-sa@${project-id}.iam.gserviceaccount.com 
        syncRepo: "https://source.developers.google.com/p/my-awesome-project/r/my-awesome-project-migrate-demo" # kpt-set: https://source.developers.google.com/p/${project-id}/r/${project-id}-migrate-demo
        syncRev: "HEAD"
        syncBranch: "master"
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
      auditIntervalSeconds: "20"
    binauthz:
      enabled: true
    hierarchyController:
      enabled: false
      enablePodTreeLabels: false
      enableHierarchicalResourceQuota: false
    version: 1.10.2
