apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  labels:
    label-one: value-one
  name: migrate-service-cluster
  annotations:
    cnrm.cloud.google.com/project-id: "my-awesome-project" # kpt-set: ${project-id}    
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
  namespace: config-control # kpt-set: ${project-namespace}
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/my-awesome-project/locations/northamerica-northeast1/clusters/migrate-service-cluster # kpt-set: https://container.googleapis.com/v1/projects/${project-id}/locations/northamerica-northeast1/clusters/migrate-service-cluster
  description: migrate-service-cluster
  endpoint:
    gkeCluster:
      resourceRef:
        name: migrate-service-cluster
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  labels:
    label-one: value-one
  name: migrate-service-cluster-2
  annotations:
    cnrm.cloud.google.com/project-id: "my-awesome-project" # kpt-set: ${project-id}  
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
  namespace: config-control # kpt-set: ${project-namespace}
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/my-awesome-project/locations/northamerica-northeast2/clusters/migrate-service-cluster-2 # kpt-set: https://container.googleapis.com/v1/projects/${project-id}/locations/northamerica-northeast2/clusters/migrate-service-cluster-2
  description: migrate-service-cluster-2
  endpoint:
    gkeCluster:
      resourceRef:
        name: migrate-service-cluster-2
