apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: servicemesh
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  projectRef:
    external: my-awesome-project # kpt-set: ${project-id}    
  location: global
  resourceID: servicemesh
